name: Create Wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install wheel twine setuptools

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Upload wheel to release
      uses: softprops/action-gh-release@v2
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{env.RELEASE_TAG}}
        # token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/*.whl
